# TARGET(name for a certain operation): PREREQUISITES
# TAB in commands 

# make
# as we have only one target below target will be executed
build:
	g++ hello_world.cpp -o hello_world

# make
# first target will be executed

# make execute
# or
# make build 
execute:
	./hello_world

clean:
	rm hello_world


###############
## TARGETS   ##
###############
# target: prerequisites
#	commands

# The commands are a series of steps typically to make the target,
# 	need to start with a tab character, not space
# The prerequisites are file names, separated by spaces.
# 	These files need to exist before the commands for the target are run.
# clean is often used as a target that removes the output of other targets